export const data = {
  dogs: [
    {
      image: "https://images.dog.ceo/breeds/kelpie/n02105412_7843.jpg",
      name: "Katharina",
      breed: "kelpie",
      ownerId: 9,
      id: 0,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-lakeland/n02095570_4171.jpg",
      name: "Hayley",
      breed: "lakeland terrier",
      ownerId: 15,
      id: 1,
    },
    {
      image: "https://images.dog.ceo/breeds/husky/n02110185_13282.jpg",
      name: "Hudson",
      breed: "husky",
      ownerId: 2,
      id: 2,
    },
    {
      image: "https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg",
      name: "Kathryne",
      breed: "lapphund finnish",
      ownerId: 1,
      id: 3,
    },
    {
      image: "https://images.dog.ceo/breeds/chow/n02112137_8492.jpg",
      name: "Vito",
      breed: "chow",
      ownerId: 14,
      id: 4,
    },
    {
      image: "https://images.dog.ceo/breeds/spaniel-sussex/n02102480_6047.jpg",
      name: "Damaris",
      breed: "sussex spaniel",
      ownerId: 0,
      id: 5,
    },
    {
      image: "https://images.dog.ceo/breeds/borzoi/n02090622_7619.jpg",
      name: "Sister",
      breed: "borzoi",
      ownerId: 15,
      id: 6,
    },
    {
      image: "https://images.dog.ceo/breeds/labradoodle/lola.jpg",
      name: "Arden",
      breed: "labradoodle",
      ownerId: 3,
      id: 7,
    },
    {
      image:
        "https://images.dog.ceo/breeds/spaniel-japanese/n02085782_4208.jpg",
      name: "Schuyler",
      breed: "japanese spaniel",
      ownerId: 0,
      id: 8,
    },
    {
      image:
        "https://images.dog.ceo/breeds/pinscher-miniature/n02107312_1794.jpg",
      name: "Adell",
      breed: "miniature pinscher",
      ownerId: 5,
      id: 9,
    },
    {
      image: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_275.jpg",
      name: "Olen",
      breed: "bernese mountain",
      ownerId: 4,
      id: 10,
    },
    {
      image: "https://images.dog.ceo/breeds/eskimo/n02109961_658.jpg",
      name: "Chelsie",
      breed: "eskimo",
      ownerId: 1,
      id: 11,
    },
    {
      image: "https://images.dog.ceo/breeds/spaniel-sussex/n02102480_4544.jpg",
      name: "Cara",
      breed: "sussex spaniel",
      ownerId: 7,
      id: 12,
    },
    {
      image: "https://images.dog.ceo/breeds/segugio-italian/n02090722_002.jpg",
      name: "Orion",
      breed: "italian segugio",
      ownerId: 9,
      id: 13,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-westhighland/n02098286_6205.jpg",
      name: "Jordan",
      breed: "westhighland terrier",
      ownerId: 14,
      id: 14,
    },
    {
      image: "https://images.dog.ceo/breeds/bluetick/n02088632_686.jpg",
      name: "Rosie",
      breed: "bluetick",
      ownerId: 13,
      id: 15,
    },
    {
      image:
        "https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_2447.jpg",
      name: "Damien",
      breed: "flatcoated retriever",
      ownerId: 5,
      id: 16,
    },
    {
      image: "https://images.dog.ceo/breeds/bulldog-english/bunz.jpg",
      name: "Eleanora",
      breed: "english bulldog",
      ownerId: 2,
      id: 17,
    },
    {
      image: "https://images.dog.ceo/breeds/mix/xeshaBelka_(39).jpg",
      name: "Mable",
      breed: "mix",
      ownerId: 1,
      id: 18,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-sealyham/n02095889_4116.jpg",
      name: "Axel",
      breed: "sealyham terrier",
      ownerId: 6,
      id: 19,
    },
    {
      image: "https://images.dog.ceo/breeds/chihuahua/n02085620_4290.jpg",
      name: "Ladarius",
      breed: "chihuahua",
      ownerId: 14,
      id: 20,
    },
    {
      image:
        "https://images.dog.ceo/breeds/retriever-chesapeake/n02099849_2092.jpg",
      name: "Amanda",
      breed: "chesapeake retriever",
      ownerId: 12,
      id: 21,
    },
    {
      image: "https://images.dog.ceo/breeds/airedale/n02096051_2333.jpg",
      name: "Cordia",
      breed: "airedale",
      ownerId: 11,
      id: 22,
    },
    {
      image: "https://images.dog.ceo/breeds/poodle-toy/n02113624_2508.jpg",
      name: "Joseph",
      breed: "toy poodle",
      ownerId: 10,
      id: 23,
    },
    {
      image: "https://images.dog.ceo/breeds/collie-border/n02106166_1754.jpg",
      name: "Vicente",
      breed: "border collie",
      ownerId: 4,
      id: 24,
    },
    {
      image: "https://images.dog.ceo/breeds/hound-plott/hhh_plott002.jpg",
      name: "Sarah",
      breed: "plott hound",
      ownerId: 11,
      id: 25,
    },
    {
      image: "https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg",
      name: "Eloise",
      breed: "lapphund finnish",
      ownerId: 11,
      id: 26,
    },
    {
      image: "https://images.dog.ceo/breeds/sharpei/noel.jpg",
      name: "Herminio",
      breed: "sharpei",
      ownerId: 7,
      id: 27,
    },
    {
      image: "https://images.dog.ceo/breeds/pyrenees/n02111500_8729.jpg",
      name: "Montana",
      breed: "pyrenees",
      ownerId: 2,
      id: 28,
    },
    {
      image: "https://images.dog.ceo/breeds/whippet/n02091134_1425.jpg",
      name: "Salvador",
      breed: "whippet",
      ownerId: 12,
      id: 29,
    },
    {
      image: "https://images.dog.ceo/breeds/pembroke/n02113023_6801.jpg",
      name: "Luis",
      breed: "pembroke",
      ownerId: 14,
      id: 30,
    },
    {
      image: "https://images.dog.ceo/breeds/spaniel-welsh/n02102177_1039.jpg",
      name: "Edgardo",
      breed: "welsh spaniel",
      ownerId: 0,
      id: 31,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-norfolk/n02094114_2125.jpg",
      name: "Ryder",
      breed: "norfolk terrier",
      ownerId: 0,
      id: 32,
    },
    {
      image: "https://images.dog.ceo/breeds/mountain-swiss/n02107574_2998.jpg",
      name: "Delmer",
      breed: "swiss mountain",
      ownerId: 11,
      id: 33,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-norwich/n02094258_2047.jpg",
      name: "Alisa",
      breed: "norwich terrier",
      ownerId: 3,
      id: 34,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-norfolk/n02094114_382.jpg",
      name: "Jade",
      breed: "norfolk terrier",
      ownerId: 7,
      id: 35,
    },
    {
      image: "https://images.dog.ceo/breeds/keeshond/n02112350_8713.jpg",
      name: "Monserrate",
      breed: "keeshond",
      ownerId: 1,
      id: 36,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-dandie/n02096437_3603.jpg",
      name: "Tyrel",
      breed: "dandie terrier",
      ownerId: 2,
      id: 37,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-tibetan/n02097474_494.jpg",
      name: "Gerhard",
      breed: "tibetan terrier",
      ownerId: 14,
      id: 38,
    },
    {
      image: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_2131.jpg",
      name: "Kasey",
      breed: "irish wolfhound",
      ownerId: 0,
      id: 39,
    },
    {
      image: "https://images.dog.ceo/breeds/husky/n02110185_9461.jpg",
      name: "Hailee",
      breed: "husky",
      ownerId: 10,
      id: 40,
    },
    {
      image: "https://images.dog.ceo/breeds/otterhound/n02091635_4697.jpg",
      name: "Demario",
      breed: "otterhound",
      ownerId: 10,
      id: 41,
    },
    {
      image: "https://images.dog.ceo/breeds/setter-english/n02100735_6140.jpg",
      name: "Garnet",
      breed: "english setter",
      ownerId: 12,
      id: 42,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-fox/n02095314_493.jpg",
      name: "Betsy",
      breed: "fox terrier",
      ownerId: 7,
      id: 43,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-irish/n02093991_4670.jpg",
      name: "Roberto",
      breed: "irish terrier",
      ownerId: 6,
      id: 44,
    },
    {
      image: "https://images.dog.ceo/breeds/labradoodle/lola.jpg",
      name: "Yasmin",
      breed: "labradoodle",
      ownerId: 4,
      id: 45,
    },
    {
      image:
        "https://images.dog.ceo/breeds/springer-english/n02102040_5145.jpg",
      name: "Ottis",
      breed: "english springer",
      ownerId: 4,
      id: 46,
    },
    {
      image: "https://images.dog.ceo/breeds/airedale/n02096051_4902.jpg",
      name: "Bessie",
      breed: "airedale",
      ownerId: 13,
      id: 47,
    },
    {
      image: "https://images.dog.ceo/breeds/saluki/n02091831_7066.jpg",
      name: "Ahmad",
      breed: "saluki",
      ownerId: 6,
      id: 48,
    },
    {
      image: "https://images.dog.ceo/breeds/mountain-swiss/n02107574_1180.jpg",
      name: "Elise",
      breed: "swiss mountain",
      ownerId: 7,
      id: 49,
    },
    {
      image: "https://images.dog.ceo/breeds/pointer-germanlonghair/hans4.jpg",
      name: "Jermey",
      breed: "germanlonghair pointer",
      ownerId: 2,
      id: 50,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_3431.jpg",
      name: "Mariam",
      breed: "yorkshire terrier",
      ownerId: 5,
      id: 51,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-norfolk/n02094114_3935.jpg",
      name: "Renee",
      breed: "norfolk terrier",
      ownerId: 13,
      id: 52,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-irish/n02093991_3453.jpg",
      name: "Rosella",
      breed: "irish terrier",
      ownerId: 10,
      id: 53,
    },
    {
      image: "https://images.dog.ceo/breeds/malamute/n02110063_13798.jpg",
      name: "Heidi",
      breed: "malamute",
      ownerId: 3,
      id: 54,
    },
    {
      image: "https://images.dog.ceo/breeds/groenendael/n02105056_3666.jpg",
      name: "Augusta",
      breed: "groenendael",
      ownerId: 11,
      id: 55,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-american/n02093428_2574.jpg",
      name: "Wilton",
      breed: "american terrier",
      ownerId: 1,
      id: 56,
    },
    {
      image: "https://images.dog.ceo/breeds/papillon/n02086910_7752.jpg",
      name: "Ashleigh",
      breed: "papillon",
      ownerId: 9,
      id: 57,
    },
    {
      image: "https://images.dog.ceo/breeds/buhund-norwegian/hakon1.jpg",
      name: "Freda",
      breed: "norwegian buhund",
      ownerId: 13,
      id: 58,
    },
    {
      image: "https://images.dog.ceo/breeds/kuvasz/n02104029_593.jpg",
      name: "Thomas",
      breed: "kuvasz",
      ownerId: 12,
      id: 59,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-bedlington/n02093647_2306.jpg",
      name: "Elise",
      breed: "bedlington terrier",
      ownerId: 12,
      id: 60,
    },
    {
      image: "https://images.dog.ceo/breeds/brabancon/n02112706_1057.jpg",
      name: "Retta",
      breed: "brabancon",
      ownerId: 13,
      id: 61,
    },
    {
      image: "https://images.dog.ceo/breeds/hound-walker/n02089867_2388.jpg",
      name: "Alexis",
      breed: "walker hound",
      ownerId: 8,
      id: 62,
    },
    {
      image: "https://images.dog.ceo/breeds/chihuahua/n02085620_5093.jpg",
      name: "Kaycee",
      breed: "chihuahua",
      ownerId: 7,
      id: 63,
    },
    {
      image:
        "https://images.dog.ceo/breeds/poodle-medium/WhatsApp_Image_2022-08-06_at_4.48.38_PM.jpg",
      name: "Genevieve",
      breed: "medium poodle",
      ownerId: 12,
      id: 64,
    },
    {
      image:
        "https://images.dog.ceo/breeds/ridgeback-rhodesian/n02087394_1274.jpg",
      name: "Dagmar",
      breed: "rhodesian ridgeback",
      ownerId: 13,
      id: 65,
    },
    {
      image:
        "https://images.dog.ceo/breeds/havanese/00100trPORTRAIT_00100_BURST20191126134713895_COVER.jpg",
      name: "Cara",
      breed: "havanese",
      ownerId: 3,
      id: 66,
    },
    {
      image: "https://images.dog.ceo/breeds/cattledog-australian/IMG_1042.jpg",
      name: "Karolann",
      breed: "australian cattledog",
      ownerId: 12,
      id: 67,
    },
    {
      image: "https://images.dog.ceo/breeds/bouvier/n02106382_4503.jpg",
      name: "Destini",
      breed: "bouvier",
      ownerId: 6,
      id: 68,
    },
    {
      image: "https://images.dog.ceo/breeds/spitz-japanese/tofu.jpg",
      name: "Elenor",
      breed: "japanese spitz",
      ownerId: 6,
      id: 69,
    },
    {
      image:
        "https://images.dog.ceo/breeds/sheepdog-english/n02105641_6350.jpg",
      name: "Timmy",
      breed: "english sheepdog",
      ownerId: 10,
      id: 70,
    },
    {
      image: "https://images.dog.ceo/breeds/dingo/n02115641_7355.jpg",
      name: "Christophe",
      breed: "dingo",
      ownerId: 12,
      id: 71,
    },
    {
      image: "https://images.dog.ceo/breeds/otterhound/n02091635_2287.jpg",
      name: "Bennie",
      breed: "otterhound",
      ownerId: 15,
      id: 72,
    },
    {
      image: "https://images.dog.ceo/breeds/australian-shepherd/forest.jpg",
      name: "Ludwig",
      breed: "shepherd australian",
      ownerId: 4,
      id: 73,
    },
    {
      image: "https://images.dog.ceo/breeds/bulldog-french/n02108915_198.jpg",
      name: "Colt",
      breed: "french bulldog",
      ownerId: 6,
      id: 74,
    },
    {
      image: "https://images.dog.ceo/breeds/boxer/n02108089_5977.jpg",
      name: "Keshawn",
      breed: "boxer",
      ownerId: 11,
      id: 75,
    },
    {
      image: "https://images.dog.ceo/breeds/bulldog-french/n02108915_977.jpg",
      name: "Elva",
      breed: "french bulldog",
      ownerId: 8,
      id: 76,
    },
    {
      image: "https://images.dog.ceo/breeds/borzoi/n02090622_1786.jpg",
      name: "Tess",
      breed: "borzoi",
      ownerId: 0,
      id: 77,
    },
    {
      image: "https://images.dog.ceo/breeds/cockapoo/Guri2.jpg",
      name: "Alysson",
      breed: "cockapoo",
      ownerId: 14,
      id: 78,
    },
    {
      image: "https://images.dog.ceo/breeds/poodle-standard/n02113799_1444.jpg",
      name: "Jevon",
      breed: "standard poodle",
      ownerId: 6,
      id: 79,
    },
    {
      image:
        "https://images.dog.ceo/breeds/elkhound-norwegian/n02091467_7095.jpg",
      name: "Joy",
      breed: "norwegian elkhound",
      ownerId: 10,
      id: 80,
    },
    {
      image: "https://images.dog.ceo/breeds/bulldog-french/n02108915_977.jpg",
      name: "Fiona",
      breed: "french bulldog",
      ownerId: 7,
      id: 81,
    },
    {
      image: "https://images.dog.ceo/breeds/spaniel-irish/n02102973_720.jpg",
      name: "Dortha",
      breed: "irish spaniel",
      ownerId: 1,
      id: 82,
    },
    {
      image: "https://images.dog.ceo/breeds/hound-blood/n02088466_10335.jpg",
      name: "Desiree",
      breed: "blood hound",
      ownerId: 9,
      id: 83,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-cairn/n02096177_1434.jpg",
      name: "Alvis",
      breed: "cairn terrier",
      ownerId: 8,
      id: 84,
    },
    {
      image: "https://images.dog.ceo/breeds/schipperke/n02104365_5411.jpg",
      name: "Lilla",
      breed: "schipperke",
      ownerId: 14,
      id: 85,
    },
    {
      image: "https://images.dog.ceo/breeds/redbone/n02090379_855.jpg",
      name: "Colten",
      breed: "redbone",
      ownerId: 15,
      id: 86,
    },
    {
      image:
        "https://images.dog.ceo/breeds/terrier-westhighland/n02098286_3432.jpg",
      name: "Madison",
      breed: "westhighland terrier",
      ownerId: 14,
      id: 87,
    },
    {
      image: "https://images.dog.ceo/breeds/hound-ibizan/n02091244_3161.jpg",
      name: "Luz",
      breed: "ibizan hound",
      ownerId: 9,
      id: 88,
    },
    {
      image: "https://images.dog.ceo/breeds/mastiff-bull/n02108422_3647.jpg",
      name: "Jesus",
      breed: "bull mastiff",
      ownerId: 6,
      id: 89,
    },
    {
      image: "https://images.dog.ceo/breeds/borzoi/n02090622_8745.jpg",
      name: "Candelario",
      breed: "borzoi",
      ownerId: 13,
      id: 90,
    },
    {
      image: "https://images.dog.ceo/breeds/cockapoo/Guri2.jpg",
      name: "Colin",
      breed: "cockapoo",
      ownerId: 15,
      id: 91,
    },
    {
      image: "https://images.dog.ceo/breeds/pointer-germanlonghair/hans1.jpg",
      name: "Sheldon",
      breed: "germanlonghair pointer",
      ownerId: 14,
      id: 92,
    },
    {
      image: "https://images.dog.ceo/breeds/wolfhound-irish/n02090721_2235.jpg",
      name: "Lenna",
      breed: "irish wolfhound",
      ownerId: 9,
      id: 93,
    },
    {
      image: "https://images.dog.ceo/breeds/malamute/n02110063_8514.jpg",
      name: "Millie",
      breed: "malamute",
      ownerId: 12,
      id: 94,
    },
    {
      image:
        "https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg",
      name: "Danyka",
      breed: "pitbull",
      ownerId: 4,
      id: 95,
    },
    {
      image: "https://images.dog.ceo/breeds/eskimo/n02109961_1351.jpg",
      name: "Cristobal",
      breed: "eskimo",
      ownerId: 7,
      id: 96,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-welsh/lucy.jpg",
      name: "Rodger",
      breed: "welsh terrier",
      ownerId: 13,
      id: 97,
    },
    {
      image: "https://images.dog.ceo/breeds/rottweiler/n02106550_6599.jpg",
      name: "Moshe",
      breed: "rottweiler",
      ownerId: 5,
      id: 98,
    },
    {
      image: "https://images.dog.ceo/breeds/terrier-russell/little1.jpg",
      name: "Margaretta",
      breed: "russell terrier",
      ownerId: 11,
      id: 99,
    },
  ],
  owners: [
    { id: 0, name: "Sherman DuBuque", job: "Customer Marketing Planner" },
    { id: 1, name: "Martha Raynor", job: "Chief Solutions Producer" },
    {
      id: 2,
      name: "Jenna Beatty",
      job: "International Quality Associate",
    },
    {
      id: 3,
      name: "Mr. Steve VonRueden IV",
      job: "Customer Infrastructure Executive",
    },
    {
      id: 4,
      name: "Cecil Reichel",
      job: "Legacy Integration Coordinator",
    },
    { id: 5, name: "Grace Morar", job: "Global Creative Manager" },
    { id: 6, name: "Jenny Pollich", job: "District Security Assistant" },
    {
      id: 7,
      name: "Krystal Cruickshank",
      job: "International Infrastructure Manager",
    },
    { id: 8, name: "Jane Rodriguez", job: "Future Accounts Engineer" },
    {
      id: 9,
      name: "Mrs. Rudolph Legros",
      job: "Principal Data Executive",
    },
    {
      id: 10,
      name: "Lucy Jerde",
      job: "Central Communications Assistant",
    },
    {
      id: 11,
      name: "Fernando Larkin II",
      job: "Principal Brand Developer",
    },
    {
      id: 12,
      name: "Miss Gabriel Rolfson",
      job: "Human Accounts Liaison",
    },
    { id: 13, name: "Danny Prohaska", job: "Investor Accounts Analyst" },
    {
      id: 14,
      name: "Pat Collier",
      job: "Global Accountability Developer",
    },
    {
      id: 15,
      name: "Ethel Bailey",
      job: "Regional Identity Orchestrator",
    },
  ],
};
