import { Dog, Owner } from "./types";

/**
 * This could be generated by OpenAPI
 */
export class BackendAPIClient {
  host: string;
  constructor(host: string) {
    this.host = host;
  }
  async getDogs(offset: number): Promise<Dog[]> {
    return fetch(
      `${this.host}/api/dogs?${new URLSearchParams({
        offset: String(offset),
      })}`
    ).then((r) => r.json());
  }

  async getOwner(id: number): Promise<Owner> {
    return fetch(`${this.host}/api/owner/${id}`).then((r) => r.json());
  }

  async getOwners(ids: number[]): Promise<Owner[]> {
    return fetch(
      `${this.host}/api/owner/bulk?${new URLSearchParams(
        ids.map((id) => ["ids", String(id)])
      )}`
    ).then((r) => r.json());
  }
}
